const dashboardStyles = {
  page:          { minHeight: "100vh", background: "#f0f2f5", fontFamily: "'Segoe UI', sans-serif" },
  navbar:        { background: "#fff", borderBottom: "1px solid #e2e8f0", padding: "0 2rem", height: "64px", display: "flex", alignItems: "center", justifyContent: "space-between", position: "sticky", top: 0, zIndex: 10 },
  navBrand:      { display: "flex", alignItems: "center", gap: "10px" },
  navTitle:      { fontSize: "17px", fontWeight: "700", color: "#2563EB" },
  navLinks:      { display: "flex", gap: "2rem" },
  navLink:       { fontSize: "14px", color: "#64748b", cursor: "pointer", padding: "4px 0", display: "flex", alignItems: "center" },
  navLinkActive: { fontSize: "14px", color: "#2563EB", cursor: "pointer", padding: "4px 0", fontWeight: "600", borderBottom: "2px solid #2563EB", display: "flex", alignItems: "center" },
  logoutBtn:     { padding: "8px 18px", background: "none", border: "1.5px solid #e2e8f0", borderRadius: "10px", fontSize: "13px", color: "#64748b", cursor: "pointer", display: "flex", alignItems: "center" },
  content:       { padding: "2rem" },
  header:        { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "1.5rem" },
  headerSub:     { fontSize: "11px", fontWeight: "700", color: "#94a3b8", letterSpacing: "0.08em", margin: "0 0 4px" },
  pageTitle:     { fontSize: "26px", fontWeight: "700", color: "#1e293b", margin: 0 },
  totalBadge:    { background: "#2563EB", borderRadius: "14px", padding: "12px 20px", textAlign: "center" },
  totalNum:      { display: "block", fontSize: "28px", fontWeight: "700", color: "#fff" },
  totalLabel:    { fontSize: "11px", color: "rgba(255,255,255,0.7)", fontWeight: "600" },
  select:        { padding: "8px 12px", borderRadius: "10px", border: "1px solid #e2e8f0", fontSize: "14px", color: "#1e293b", outline: "none", cursor: "pointer", background: "#fff" },
  loading:       { textAlign: "center", color: "#94a3b8", marginTop: "3rem" },
  statsGrid:     { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "16px", marginBottom: "1.5rem" },
  statCard:      { background: "#fff", borderRadius: "16px", padding: "1.25rem 1.5rem", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" },
  statLabel:     { fontSize: "11px", fontWeight: "700", color: "#94a3b8", letterSpacing: "0.05em", marginBottom: "8px" },
  statNum:       { fontSize: "28px", fontWeight: "700" },
  row:           { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" },
  card:          { background: "#fff", borderRadius: "16px", padding: "1.5rem", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" },
  cardTitle:     { fontSize: "15px", fontWeight: "700", color: "#1e293b", marginBottom: "1.25rem" },
  breakdownRow:  { display: "flex", alignItems: "center", gap: "10px", marginBottom: "14px" },
  breakdownLabel:{ fontSize: "12px", color: "#64748b", width: "55px", flexShrink: 0 },
  barTrack:      { flex: 1, height: "8px", background: "#f1f5f9", borderRadius: "4px", overflow: "hidden" },
  barFill:       { height: "100%", borderRadius: "4px" },
};

export default dashboardStyles;